In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
dataset_path = "/content/drive/MyDrive/Projetos_ion/ION_Prospeccao_Inteligente/datasets/VetBr/dataset_mg_vetbr1.csv"
clients_path = "/content/drive/MyDrive/Projetos_ion/ION_Prospeccao_Inteligente/datasets/VetBr/estabelecimentos_empresas_vetbr_filial1_todos.csv"

In [4]:
df_cli = pd.read_csv(clients_path, dtype=str)
df_cli.head()

,cnpj,cnpj_basico,identificador_matriz_filial,data_inicio_atividade,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,tipo_logradouro,logradouro,numero,complemento,bairro,cep,uf,municipio,capital_social,porte
0,35.471.883/0001-00,35471883,MATRIZ,20191111,4789004,Comércio varejista de animais vivos e de artig...,"4712100,4713002,4744099,4771704,4789099",AVENIDA,ESAU LACERDA,2103,NaN,MUTAMBA,62810000,CE,ICAPUI,5000.0,01
1,35.509.080/0001-90,35509080,MATRIZ,20191113,4744099,Comércio varejista de materiais de construção ...,"4541206,4721103,4530703,4789005",RUA,CASTANHEIRA,373,NaN,FLORESTA,35170230,MG,CORONEL FABRICIANO,1000.0,01
2,35.562.380/0001-32,35562380,MATRIZ,20191120,4789004,Comércio varejista de animais vivos e de artig...,"4771704,4772500,4781400,9609208",RUA,PRIMEIRO DE SETEMBRO,265,NaN,CENTRO,08715080,SP,MOGI DAS CRUZES,10000.0,01
3,35.589.544/0001-15,35589544,MATRIZ,20191122,7500100,Atividades veterinárias,"4789004,9609207,9609208",RUA,VICENTE LEPORACE,1534,NaN,CAMPO BELO,04619034,SP,SAO PAULO,100000.0,03
4,29.019.542/0001-98,29019542,MATRIZ,20171107,7500100,Atividades veterinárias,"4771704,4789004,8599604,9609207,9609208",RUA,PRESIDENTE GETULIO VARGAS,345,SALA 1,CENTRO,12010500,SP,TAUBATE,5000.0,01

In [ ]:
df_cli.shape

(13100, 17)

In [5]:
df_cnpj = pd.read_csv('/content/drive/MyDrive/Projetos_ion/ION_Prospeccao_Inteligente/datasets/VetBr/cnpj_filial1_vetbr.csv', dtype=str)
df_cnpj.head()

,CODCLI,RAZAOSOCIAL,FANTASIA,CNPJ,CODFILIAL
0,13,ABASTECIMENTOS OLIVEIRA CAMPOS LTDA,PONTO DO CRIADOR,04.735.078/0001-05,1.0
1,16,ADAO MARCELINO DE LACERDA,AGROPECUARIA LACERDA,05.309.143/0001-01,1.0
2,19,CASA DO RURALISTA LTDA,CASA DO RURALISTA,19.600.212/0001-38,1.0
3,20,MARCOS ANTONIO MUNIZ,CASA DO AGRICULTOR,03.637.281/0001-86,1.0
4,22,ADEMIR APARECIDO CONSTANTINO,NaN,04.162.718/0001-35,1.0

In [6]:
df_cnpj.rename(columns={'CNPJ': 'cnpj'}, inplace=True)

In [7]:
df_merge = pd.merge(df_cli, df_cnpj, how='left', on='cnpj')
df_merge.head()

,cnpj,cnpj_basico,identificador_matriz_filial,data_inicio_atividade,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,tipo_logradouro,logradouro,numero,complemento,bairro,cep,uf,municipio,capital_social,porte,CODCLI,RAZAOSOCIAL,FANTASIA,CODFILIAL
0,35.471.883/0001-00,35471883,MATRIZ,20191111,4789004,Comércio varejista de animais vivos e de artig...,"4712100,4713002,4744099,4771704,4789099",AVENIDA,ESAU LACERDA,2103,NaN,MUTAMBA,62810000,CE,ICAPUI,5000.0,01,277098,ROBERTO DA COSTA LIMA,NaN,1.0
1,35.509.080/0001-90,35509080,MATRIZ,20191113,4744099,Comércio varejista de materiais de construção ...,"4541206,4721103,4530703,4789005",RUA,CASTANHEIRA,373,NaN,FLORESTA,35170230,MG,CORONEL FABRICIANO,1000.0,01,138019,ANGELO EMANUEL SOUZA ROQUE 12815576686,DISTRIBUIDORA SOUZA,1.0
2,35.562.380/0001-32,35562380,MATRIZ,20191120,4789004,Comércio varejista de animais vivos e de artig...,"4771704,4772500,4781400,9609208",RUA,PRIMEIRO DE SETEMBRO,265,NaN,CENTRO,08715080,SP,MOGI DAS CRUZES,10000.0,01,135318,EDGAR BAPTISTA DE SIQUEIRA,DIPATAS,1.0
3,35.589.544/0001-15,35589544,MATRIZ,20191122,7500100,Atividades veterinárias,"4789004,9609207,9609208",RUA,VICENTE LEPORACE,1534,NaN,CAMPO BELO,04619034,SP,SAO PAULO,100000.0,03,141968,PETIT MAISON PET SHOP LTDA,PETIT MAISON,1.0
4,29.019.542/0001-98,29019542,MATRIZ,20171107,7500100,Atividades veterinárias,"4771704,4789004,8599604,9609207,9609208",RUA,PRESIDENTE GETULIO VARGAS,345,SALA 1,CENTRO,12010500,SP,TAUBATE,5000.0,01,153003,LUCAS SANTOS AMARAL,VITTA HOSPITAL VETERINARIO E CENTRO DE T,1.0

In [8]:
df_merge.dropna(subset=['CODFILIAL'], inplace=True)

In [9]:
desired_cols = [
    'cnpj',
    'idade_empresa',
    'capital_social',
    'porte',
    'cnae'
]
cnae_categories = ['Seção', 'Divisão', 'Grupo', 'Classe']
sec_cnaes = [f"cnae_sec_{i + 1}" for i in range(5)]
sec_cnaes_categories = [f"{cat}{i + 1}" for i in range(5) for cat in cnae_categories]

desired_cols.extend(cnae_categories)
desired_cols.extend(sec_cnaes)
desired_cols.extend(sec_cnaes_categories)
desired_cols

['cnpj',
 'idade_empresa',
 'capital_social',
 'porte',
 'cnae',
 'Seção',
 'Divisão',
 'Grupo',
 'Classe',
 'cnae_sec_1',
 'cnae_sec_2',
 'cnae_sec_3',
 'cnae_sec_4',
 'cnae_sec_5',
 'Seção1',
 'Divisão1',
 'Grupo1',
 'Classe1',
 'Seção2',
 'Divisão2',
 'Grupo2',
 'Classe2',
 'Seção3',
 'Divisão3',
 'Grupo3',
 'Classe3',
 'Seção4',
 'Divisão4',
 'Grupo4',
 'Classe4',
 'Seção5',
 'Divisão5',
 'Grupo5',
 'Classe5']

In [10]:
dataset = pd.read_csv(dataset_path, usecols=desired_cols)
dataset.head()

,cnpj,cnae,capital_social,porte,Seção,Divisão,Grupo,Classe,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5
0,35.464.865/0001-93,8230001,300.0,1.0,N,82,823.0,82300.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35.464.962/0001-86,4399103,5000.0,1.0,F,43,439.0,43991.0,1206,4321500.0,4330404.0,NaN,NaN,NaN,F,43.0,432.0,43215.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35.465.399/0001-60,4520002,5000.0,1.0,G,45,452.0,45200.0,1206,4520005.0,4399103.0,4330404.0,4330405.0,NaN,G,45.0,452.0,45200.0,F,43.0,439.0,43991.0,F,43.0,433.0,43304.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN
3,35.465.446/0001-76,9602501,1000.0,1.0,S,96,960.0,96025.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35.465.492/0001-75,7739002,2000.0,1.0,N,77,773.0,77390.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
clients = df_merge[df_merge.columns.difference(['CODCLI','RAZAOSOCIAL','FANTASIA','CODFILIAL'])]
clients.head()

,bairro,capital_social,cep,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,cnpj,cnpj_basico,complemento,data_inicio_atividade,identificador_matriz_filial,logradouro,municipio,numero,porte,tipo_logradouro,uf
0,MUTAMBA,5000.0,62810000,4789004,Comércio varejista de animais vivos e de artig...,"4712100,4713002,4744099,4771704,4789099",35.471.883/0001-00,35471883,NaN,20191111,MATRIZ,ESAU LACERDA,ICAPUI,2103,01,AVENIDA,CE
1,FLORESTA,1000.0,35170230,4744099,Comércio varejista de materiais de construção ...,"4541206,4721103,4530703,4789005",35.509.080/0001-90,35509080,NaN,20191113,MATRIZ,CASTANHEIRA,CORONEL FABRICIANO,373,01,RUA,MG
2,CENTRO,10000.0,08715080,4789004,Comércio varejista de animais vivos e de artig...,"4771704,4772500,4781400,9609208",35.562.380/0001-32,35562380,NaN,20191120,MATRIZ,PRIMEIRO DE SETEMBRO,MOGI DAS CRUZES,265,01,RUA,SP
3,CAMPO BELO,100000.0,04619034,7500100,Atividades veterinárias,"4789004,9609207,9609208",35.589.544/0001-15,35589544,NaN,20191122,MATRIZ,VICENTE LEPORACE,SAO PAULO,1534,03,RUA,SP
4,CENTRO,5000.0,12010500,7500100,Atividades veterinárias,"4771704,4789004,8599604,9609207,9609208",29.019.542/0001-98,29019542,SALA 1,20171107,MATRIZ,PRESIDENTE GETULIO VARGAS,TAUBATE,345,01,RUA,SP

In [12]:
clients.shape

(11949, 17)

In [13]:
positive_cnpjs = set(clients['cnpj'].values)

In [ ]:
positive_cnpjs

In [15]:
targets = dataset['cnpj'].apply(lambda cnpj: 1 if cnpj in positive_cnpjs else 0)

In [16]:
dataset['target'] = targets

In [ ]:
dataset.head()

,cnpj,cnpj_basico,identificador_matriz_filial,data_inicio_atividade,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,tipo_logradouro,logradouro,numero,complemento,bairro,cep,uf,municipio,capital_social,porte,Denominação,Seção,Divisão,Grupo,Classe,Subclasse,Seção_str,Divisão_str,Grupo_str,Classe_str,Subclasse_str,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5,target
0,35.464.865/0001-93,35464865,MATRIZ,20191109,8230001,"Serviços de organização de feiras, congressos,...",NaN,AREA,AVENIDA ISRAEL PINHEIRO,22,NaN,SANTA MARGARIDA,36913000,MG,SANTA MARGARIDA,300.0,1.0,"Serviços de organização de feiras, congressos,...",N,82,823.0,82300.0,8230001,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,"SERVIÇOS DE ESCRITÓRIO, DE APOIO ADMINISTRATIV...","Atividades de organização de eventos, exceto c...","Atividades de organização de eventos, exceto c...","Serviços de organização de feiras, congressos,...",1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,35.464.962/0001-86,35464962,MATRIZ,20191109,4399103,Obras de alvenaria,"4321500,4330404",RUA,BARBACENA,528,SALA 01,PENHA,37903074,MG,PASSOS,5000.0,1.0,Obras de alvenaria,F,43,439.0,43991.0,4399103,CONSTRUÇÃO,SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO,Outros serviços especializados para construção,Serviços especializados para construção não es...,Obras de alvenaria,1206,4321500.0,4330404.0,NaN,NaN,NaN,F,43.0,432.0,43215.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,35.465.399/0001-60,35465399,MATRIZ,20191109,4520002,Serviços de lanternagem ou funilaria e pintura...,"4520005,4399103,4330404,4330405",10A RUA,OLEGARIO MACIEL,315,NaN,BELA VISTA,33400000,MG,LAGOA SANTA,5000.0,1.0,Serviços de lanternagem ou funilaria e pintura...,G,45,452.0,45200.0,4520002,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,COMÉRCIO E REPARAÇÃO DE VEÍCULOS AUTOMOTORES E...,Manutenção e reparação de veículos automotores,Manutenção e reparação de veículos automotores,Serviços de lanternagem ou funilaria e pintura...,1206,4520005.0,4399103.0,4330404.0,4330405.0,NaN,G,45.0,452.0,45200.0,F,43.0,439.0,43991.0,F,43.0,433.0,43304.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN,0
3,35.465.446/0001-76,35465446,MATRIZ,20191109,9602501,"Cabeleireiros, manicure e pedicure",NaN,RUA,JOAO LUCIO,737,CASA,PROGRESSO,38178000,MG,PEDRINOPOLIS,1000.0,1.0,"Cabeleireiros, manicure e pedicure",S,96,960.0,96025.0,9602501,OUTRAS ATIVIDADES DE SERVIÇOS,OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS,Outras atividades de serviços pessoais,Cabeleireiros e outras atividades de tratament...,"Cabeleireiros, manicure e pedicure",1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,35.465.492/0001-75,35465492,MATRIZ,20191109,7739002,"Aluguel de equipamentos científicos, médicos e...",NaN,RUA,JOSE DO PATROCINIO,255,APT 405,MUNDO NOVO,36026340,MG,JUIZ DE FORA,2000.0,1.0,"Aluguel de equipamentos científicos, médicos e...",N,77,773.0,77390.0,7739002,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,ALUGUÉIS NÃO IMOBILIÁRIOS E GESTÃO DE ATIVOS I...,Aluguel de máquinas e equipamentos sem operador,Aluguel de máquinas e equipamentos não especif...,"Aluguel de equipamentos científicos, médicos e...",1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
dataset.shape

(6017111, 55)

In [17]:
dataset[dataset['target'] == 1].shape

(4713, 35)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6017111 entries, 0 to 6017110
Data columns (total 55 columns):
 #   Column                       Dtype
---  ------                       -----
 0   cnpj                         object
 1   cnpj_basico                  int64
 2   identificador_matriz_filial  object
 3   data_inicio_atividade        int64
 4   cnae                         int64
 5   cnae_fiscal_principal        object
 6   cnae_fiscal_secundaria       object
 7   tipo_logradouro              object
 8   logradouro                   object
 9   numero                       object
 10  complemento                  object
 11  bairro                       object
 12  cep                          int64
 13  uf                           object
 14  municipio                    object
 15  capital_social               float64
 16  porte                        float64
 17  Denominação                  object
 18  Seção                        object
 19  Divisão                      int64
 20  Grupo                        float64
 21  Classe                       float64
 22  Subclasse                    int64
 23  Seção_str                    object
 24  Divisão_str                  object
 25  Grupo_str                    object
 26  Classe_str                   object
 27  Subclasse_str                object
 28  idade_empresa                int64
 29  cnae_sec_1                   float64
 30  cnae_sec_2                   float64
 31  cnae_sec_3                   float64
 32  cnae_sec_4                   float64
 33  cnae_sec_5                   float64
 34  Seção1                       object
 35  Divisão1                     float64
 36  Grupo1                       float64
 37  Classe1                      float64
 38  Seção2                       object
 39  Divisão2                     float64
 40  Grupo2                       float64
 41  Classe2                      float64
 42  Seção3                       object
 43  Divisão3                     float64
 44  Grupo3                       float64
 45  Classe3                      float64
 46  Seção4                       object
 47  Divisão4                     float64
 48  Grupo4                       float64
 49  Classe4                      float64
 50  Seção5                       object
 51  Divisão5                     float64
 52  Grupo5                       float64
 53  Classe5                      float64
 54  target                       int64
dtypes: float64(24), int64(8), object(23)
memory usage: 2.5+ GB

In [ ]:
dataset.describe()

,cnae,capital_social,porte,Divisão,Grupo,Classe,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Divisão1,Grupo1,Classe1,Divisão2,Grupo2,Classe2,Divisão3,Grupo3,Classe3,Divisão4,Grupo4,Classe4,Divisão5,Grupo5,Classe5,target
count,1.674957e+06,1.674957e+06,1.674956e+06,1.674957e+06,1.622218e+06,1.622218e+06,1.674957e+06,7.166850e+05,4.350160e+05,2.802170e+05,1.935090e+05,1.400980e+05,716685.000000,716685.000000,716685.000000,435016.000000,435016.000000,435016.000000,280217.000000,280217.000000,280217.000000,193509.000000,193509.000000,193509.000000,140098.000000,140098.000000,140098.000000,1.674957e+06
mean,5.908991e+06,6.420051e+07,2.198682e+00,5.865599e+01,5.808948e+02,5.812104e+04,5.017105e+03,5.389692e+06,5.484345e+06,5.280392e+06,5.326571e+06,5.394331e+06,53.481151,538.621214,53896.805987,54.402971,548.050237,54843.322174,52.378128,527.668775,52803.791105,52.829300,532.280592,53265.557959,53.514468,539.035061,53943.156369,1.010713e-02
std,2.264956e+06,2.083944e+09,1.800275e+00,2.262460e+01,2.235766e+02,2.235785e+04,4.705969e+03,2.092700e+06,2.075695e+06,1.888827e+06,1.901292e+06,1.963157e+06,20.929091,209.255742,20926.990374,20.729170,207.510764,20756.940390,18.913244,188.880940,18888.261757,19.036523,190.132609,19012.894997,19.669756,196.300025,19631.541785,1.000249e-01
min,1.113010e+05,0.000000e+00,1.000000e+00,1.000000e+00,1.100000e+01,1.113000e+03,4.500000e+01,1.113010e+05,1.113010e+05,1.113010e+05,1.113010e+05,1.113010e+05,1.000000,11.000000,1113.000000,1.000000,11.000000,1113.000000,1.000000,11.000000,1113.000000,1.000000,11.000000,1113.000000,1.000000,11.000000,1113.000000,0.000000e+00
25%,4.721102e+06,0.000000e+00,1.000000e+00,4.700000e+01,4.710000e+02,4.712100e+04,1.366000e+03,4.635402e+06,4.635402e+06,4.530705e+06,4.541202e+06,4.530705e+06,46.000000,463.000000,46354.000000,46.000000,463.000000,46354.000000,45.000000,453.000000,45307.000000,45.000000,454.000000,45412.000000,45.000000,453.000000,45307.000000,0.000000e+00
50%,4.789004e+06,1.000000e+03,1.000000e+00,4.700000e+01,4.780000e+02,4.783100e+04,3.409000e+03,4.772500e+06,4.772500e+06,4.763601e+06,4.763604e+06,4.772500e+06,47.000000,477.000000,47725.000000,47.000000,477.000000,47725.000000,47.000000,476.000000,47636.000000,47.000000,476.000000,47636.000000,47.000000,477.000000,47725.000000,0.000000e+00
75%,8.219999e+06,1.000000e+04,5.000000e+00,8.200000e+01,7.910000e+02,7.911200e+04,7.518000e+03,6.202300e+06,6.821801e+06,6.141800e+06,6.209100e+06,6.822600e+06,62.000000,620.000000,62023.000000,68.000000,682.000000,68218.000000,61.000000,614.000000,61418.000000,62.000000,620.000000,62091.000000,68.000000,682.000000,68226.000000,0.000000e+00
max,9.900800e+06,2.620188e+11,5.000000e+00,9.900000e+01,9.900000e+02,9.900800e+04,4.461800e+04,9.900800e+06,9.900800e+06,9.900800e+06,9.900800e+06,9.700500e+06,99.000000,990.000000,99008.000000,99.000000,990.000000,99008.000000,99.000000,990.000000,99008.000000,99.000000,990.000000,99008.000000,97.000000,970.000000,97005.000000,1.000000e+00

In [ ]:
dataset.dtypes

cnpj               object
cnae                int64
capital_social    float64
porte             float64
Seção              object
Divisão             int64
Grupo             float64
Classe            float64
idade_empresa       int64
cnae_sec_1        float64
cnae_sec_2        float64
cnae_sec_3        float64
cnae_sec_4        float64
cnae_sec_5        float64
Seção1             object
Divisão1          float64
Grupo1            float64
Classe1           float64
Seção2             object
Divisão2          float64
Grupo2            float64
Classe2           float64
Seção3             object
Divisão3          float64
Grupo3            float64
Classe3           float64
Seção4             object
Divisão4          float64
Grupo4            float64
Classe4           float64
Seção5             object
Divisão5          float64
Grupo5            float64
Classe5           float64
target              int64
dtype: object

In [19]:
dataset = dataset[['cnpj','cnae','capital_social','porte','Seção',
         'Divisão','Grupo','Classe','idade_empresa','cnae_sec_1',
         'cnae_sec_2','cnae_sec_3','cnae_sec_4','cnae_sec_5','Seção1',
        'Divisão1','Grupo1','Classe1','Seção2','Divisão2','Grupo2',
         'Classe2','Seção3','Divisão3','Grupo3','Classe3','Seção4',
         'Divisão4','Grupo4','Classe4','Seção5','Divisão5','Grupo5','Classe5','target']]

dataset.head()

,cnpj,cnae,capital_social,porte,Seção,Divisão,Grupo,Classe,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5,target
0,35.464.865/0001-93,8230001,300.0,1.0,N,82,823.0,82300.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,35.464.962/0001-86,4399103,5000.0,1.0,F,43,439.0,43991.0,1206,4321500.0,4330404.0,NaN,NaN,NaN,F,43.0,432.0,43215.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,35.465.399/0001-60,4520002,5000.0,1.0,G,45,452.0,45200.0,1206,4520005.0,4399103.0,4330404.0,4330405.0,NaN,G,45.0,452.0,45200.0,F,43.0,439.0,43991.0,F,43.0,433.0,43304.0,F,43.0,433.0,43304.0,NaN,NaN,NaN,NaN,0
3,35.465.446/0001-76,9602501,1000.0,1.0,S,96,960.0,96025.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,35.465.492/0001-75,7739002,2000.0,1.0,N,77,773.0,77390.0,1206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [20]:
dataset = dataset.convert_dtypes()
dataset.head()

,cnpj,cnae,capital_social,porte,Seção,Divisão,Grupo,Classe,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5,target
0,35.464.865/0001-93,8230001,300.0,1,N,82,823,82300,1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
1,35.464.962/0001-86,4399103,5000.0,1,F,43,439,43991,1206,4321500,4330404,<NA>,<NA>,<NA>,F,43,432,43215,F,43,433,43304,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
2,35.465.399/0001-60,4520002,5000.0,1,G,45,452,45200,1206,4520005,4399103,4330404,4330405,<NA>,G,45,452,45200,F,43,439,43991,F,43,433,43304,F,43,433,43304,<NA>,<NA>,<NA>,<NA>,0
3,35.465.446/0001-76,9602501,1000.0,1,S,96,960,96025,1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
4,35.465.492/0001-75,7739002,2000.0,1,N,77,773,77390,1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0

In [ ]:
#dataset.to_csv(output_dataset_path, index=False)

In [ ]:
dataset_positive = dataset[dataset['target'] == 1]
dataset_positive.head()

,cnpj,cnpj_basico,identificador_matriz_filial,data_inicio_atividade,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,tipo_logradouro,logradouro,numero,complemento,bairro,cep,uf,municipio,capital_social,porte,Denominação,Seção,Divisão,Grupo,Classe,Subclasse,Seção_str,Divisão_str,Grupo_str,Classe_str,Subclasse_str,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5,target
412,35.509.080/0001-90,35509080,MATRIZ,20191113,4744099,Comércio varejista de materiais de construção ...,"4541206,4721103,4530703,4789005",RUA,CASTANHEIRA,373,<NA>,FLORESTA,35170230,MG,CORONEL FABRICIANO,1000.0,1,Comércio varejista de materiais de construção ...,G,47,474,47440,4744099,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,COMÉRCIO VAREJISTA,Comércio varejista de material de construção,"Comércio varejista de ferragens, madeira e mat...",Comércio varejista de materiais de construção ...,1202,4541206,4721103,4530703,4789005,<NA>,G,45,454,45412,G,47,472,47211,G,45,453,45307,G,47,478,47890,<NA>,<NA>,<NA>,<NA>,1
4714,35.949.077/0001-97,35949077,MATRIZ,20200109,4789004,Comércio varejista de animais vivos e de artig...,"4771704,9609208",RUA,GUARARAPES,1298,LOJA B,PINDORAMA,30865000,MG,BELO HORIZONTE,20000.0,1,Comércio varejista de animais vivos e de artig...,G,47,478,47890,4789004,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,COMÉRCIO VAREJISTA,Comércio varejista de produtos novos não espec...,Comércio varejista de outros produtos novos nã...,Comércio varejista de animais vivos e de artig...,1145,4771704,9609208,<NA>,<NA>,<NA>,G,47,477,47717,S,96,960,96092,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1
6373,29.361.279/0001-10,29361279,MATRIZ,20180104,9609208,Higiene e embelezamento de animais domésticos,"4623109,4644302,4771704,4789004",RUA,ITAMARANDIBA,971,LOJA,BOM PASTOR,35500148,MG,DIVINOPOLIS,3000.0,1,Higiene e embelezamento de animais domésticos,S,96,960,96092,9609208,OUTRAS ATIVIDADES DE SERVIÇOS,OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS,Outras atividades de serviços pessoais,Atividades de serviços pessoais não especifica...,Higiene e embelezamento de animais domésticos,1880,4623109,4644302,4771704,4789004,<NA>,G,46,462,46231,G,46,464,46443,G,47,477,47717,G,47,478,47890,<NA>,<NA>,<NA>,<NA>,1
7873,32.770.456/0001-27,32770456,MATRIZ,20190214,4744099,Comércio varejista de materiais de construção ...,"4623106,4623109,4723700,4771704,4789002,4789099",AVENIDA,GETULIO VARGAS,543,<NA>,CENTRO,35125000,MG,TUMIRITINGA,60000.0,1,Comércio varejista de materiais de construção ...,G,47,474,47440,4744099,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,COMÉRCIO VAREJISTA,Comércio varejista de material de construção,"Comércio varejista de ferragens, madeira e mat...",Comércio varejista de materiais de construção ...,1474,4623106,4623109,4723700,4771704,4789002,G,46,462,46231,G,46,462,46231,G,47,472,47237,G,47,477,47717,G,47,478,47890,1
8394,36.332.132/0001-68,36332132,MATRIZ,20200211,9609208,Higiene e embelezamento de animais domésticos,"9609207,0322104,0159802,0321304,4789004",PRACA,DR ANTONIO CARLOS,95,FUNDOS,CENTRO,39640000,MG,BERILO,5000.0,1,Higiene e embelezamento de animais domésticos,S,96,960,96092,9609208,OUTRAS ATIVIDADES DE SERVIÇOS,OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS,Outras atividades de serviços pessoais,Atividades de serviços pessoais não especifica...,Higiene e embelezamento de animais domésticos,1112,9609207,322104,159802,321304,4789004,S,96,960,96092,A,3,32,3221,A,1,15,1598,A,3,32,3213,G,47,478,47890,1

In [ ]:
categories = ['Seção', 'Divisão', 'Grupo', 'Classe', 'cnae']

In [ ]:
clients_categories = {}

for cat in categories:
    cat_cols = [col for col in dataset_positive.columns if col.startswith(cat)]
    unique_values = pd.unique(dataset_positive[cat_cols].values.ravel('K'))
    unique_values = sorted([v for v in unique_values if not pd.isna(v)])
    clients_categories[cat] = unique_values

TypeError: ignored

In [ ]:
clients_categories

In [ ]:
# Pegar os não-clientes
# Para cada categoria
# Pega aqueles que não têm uma das categorias do cliente (target) (target_Seção) (target_Divisão)
# Considera eles como 0

In [ ]:
for cat, values in clients_categories.items():
    cat_cols = [col for col in dataset.columns if col.startswith(cat)]
    cat_targets = pd.np.where(dataset[cat_cols].isin(values).any(1), -1, 0)
    dataset[f'target_{cat}'] = cat_targets
    dataset.loc[dataset['cnpj'].isin(positive_cnpjs), f'target_{cat}'] = 1
    
dataset.head()

In [ ]:
dataset.head()

,cnpj,cnpj_basico,identificador_matriz_filial,data_inicio_atividade,cnae,cnae_fiscal_principal,cnae_fiscal_secundaria,tipo_logradouro,logradouro,numero,complemento,bairro,cep,uf,municipio,capital_social,porte,Denominação,Seção,Divisão,Grupo,Classe,Subclasse,Seção_str,Divisão_str,Grupo_str,Classe_str,Subclasse_str,idade_empresa,cnae_sec_1,cnae_sec_2,cnae_sec_3,cnae_sec_4,cnae_sec_5,Seção1,Divisão1,Grupo1,Classe1,Seção2,Divisão2,Grupo2,Classe2,Seção3,Divisão3,Grupo3,Classe3,Seção4,Divisão4,Grupo4,Classe4,Seção5,Divisão5,Grupo5,Classe5,target
0,35.464.865/0001-93,35464865,MATRIZ,20191109,8230001,"Serviços de organização de feiras, congressos,...",<NA>,AREA,AVENIDA ISRAEL PINHEIRO,22,<NA>,SANTA MARGARIDA,36913000,MG,SANTA MARGARIDA,300.0,1,"Serviços de organização de feiras, congressos,...",N,82,823,82300,8230001,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,"SERVIÇOS DE ESCRITÓRIO, DE APOIO ADMINISTRATIV...","Atividades de organização de eventos, exceto c...","Atividades de organização de eventos, exceto c...","Serviços de organização de feiras, congressos,...",1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
1,35.464.962/0001-86,35464962,MATRIZ,20191109,4399103,Obras de alvenaria,"4321500,4330404",RUA,BARBACENA,528,SALA 01,PENHA,37903074,MG,PASSOS,5000.0,1,Obras de alvenaria,F,43,439,43991,4399103,CONSTRUÇÃO,SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO,Outros serviços especializados para construção,Serviços especializados para construção não es...,Obras de alvenaria,1206,4321500,4330404,<NA>,<NA>,<NA>,F,43,432,43215,F,43,433,43304,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
2,35.465.399/0001-60,35465399,MATRIZ,20191109,4520002,Serviços de lanternagem ou funilaria e pintura...,"4520005,4399103,4330404,4330405",10A RUA,OLEGARIO MACIEL,315,<NA>,BELA VISTA,33400000,MG,LAGOA SANTA,5000.0,1,Serviços de lanternagem ou funilaria e pintura...,G,45,452,45200,4520002,COMÉRCIO; REPARAÇÃO DE VEÍCULOS AUTOMOTORES E ...,COMÉRCIO E REPARAÇÃO DE VEÍCULOS AUTOMOTORES E...,Manutenção e reparação de veículos automotores,Manutenção e reparação de veículos automotores,Serviços de lanternagem ou funilaria e pintura...,1206,4520005,4399103,4330404,4330405,<NA>,G,45,452,45200,F,43,439,43991,F,43,433,43304,F,43,433,43304,<NA>,<NA>,<NA>,<NA>,0
3,35.465.446/0001-76,35465446,MATRIZ,20191109,9602501,"Cabeleireiros, manicure e pedicure",<NA>,RUA,JOAO LUCIO,737,CASA,PROGRESSO,38178000,MG,PEDRINOPOLIS,1000.0,1,"Cabeleireiros, manicure e pedicure",S,96,960,96025,9602501,OUTRAS ATIVIDADES DE SERVIÇOS,OUTRAS ATIVIDADES DE SERVIÇOS PESSOAIS,Outras atividades de serviços pessoais,Cabeleireiros e outras atividades de tratament...,"Cabeleireiros, manicure e pedicure",1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0
4,35.465.492/0001-75,35465492,MATRIZ,20191109,7739002,"Aluguel de equipamentos científicos, médicos e...",<NA>,RUA,JOSE DO PATROCINIO,255,APT 405,MUNDO NOVO,36026340,MG,JUIZ DE FORA,2000.0,1,"Aluguel de equipamentos científicos, médicos e...",N,77,773,77390,7739002,ATIVIDADES ADMINISTRATIVAS E SERVIÇOS COMPLEME...,ALUGUÉIS NÃO IMOBILIÁRIOS E GESTÃO DE ATIVOS I...,Aluguel de máquinas e equipamentos sem operador,Aluguel de máquinas e equipamentos não especif...,"Aluguel de equipamentos científicos, médicos e...",1206,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0

In [21]:
dataset.target.value_counts()

0    6012398
1       4713
Name: target, dtype: Int64

In [22]:
dataset.to_csv('/content/drive/MyDrive/Projetos_ion/ION_Prospeccao_Inteligente/datasets/VetBr/vetbr_filial_target.csv', index=False)